# Generated by Django 2.1.5 on 2019-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='title',
        ),
        migrations.AddField(
            model_name='relation',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
