# Generated by Django 2.1.5 on 2019-02-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_auto_20190203_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
