# Generated by Django 2.1.7 on 2019-03-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
